/*
 * Copyright (c) 2026, Peter Abeles. All Rights Reserved.
 *
 * This file is part of Efficient Java Matrix Library (EJML).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ejml.dense.block;

import org.ejml.CodeGeneratorMisc;

import java.io.FileNotFoundException;
import java.io.PrintStream;

public class GeneratorTileMultiplication {

    String className;
    PrintStream stream;

    public GeneratorTileMultiplication( String className ) throws FileNotFoundException {
        this.className = className;
        stream = new PrintStream(className + ".java");
    }

    public void createClass() {
        printTop();

        for (int i = 0; i < 2; i++) {
            boolean hasAlpha = i == 1;
            for (Operation o : Operation.values()) {
                if (hasAlpha && o == Operation.MINUS)
                    continue;
                print_mult(hasAlpha, o);
                printDelegate(hasAlpha, o, false, false);
                print_multTransA(hasAlpha, o);
                printDelegate(hasAlpha, o, true, false);
                print_multTransB(hasAlpha, o);
                printDelegate(hasAlpha, o, false, true);
            }
        }

        stream.print("}\n");
    }

    private void printTop() {
        String foo = CodeGeneratorMisc.COPYRIGHT +
                "\n" +
                "package org.ejml.dense.block;\n" +
                "\n" +
                "import javax.annotation.Generated;\n" +
                "\n" +
                "/// Matrix multiplication for the inner row major blocks, typically inside [DMatrixRBlock].\n" +
                "///\n" +
                "/// Generated by " + getClass().getSimpleName() + ". Do not modify directly.\n" +
                "@Generated(\"" + getClass().getCanonicalName() + "\")\n" +
                "public class " + className + " {\n";

        stream.print(foo);
    }

    /// Plain shape: C op A * B
    /// Pattern: ikj order with k blocked by 4 (KB=4). The 4-FMA-fused inner j-loop
    /// is what HotSpot vectorizes well. SET is implemented as "zero C first, then
    /// accumulate" so the main loop code is identical for PLUS, MINUS, SET.
    private void print_mult( boolean hasAlpha, Operation opType ) {

        createHeader(hasAlpha, opType, false, false);

        stream.print(
                "//        for( int i = 0; i < heightA; i++ ) {\n" +
                        "//            for( int k = 0; k < widthA; k++ ) {\n" +
                        "//                for( int j = 0; j < widthC; j++ ) {\n" +
                        "//                    dataC[ i*widthC + j + indexC ] " + opString(opType) + " " + (hasAlpha ? "alpha * " : "") +
                        "dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];\n" +
                        "//                }\n" +
                        "//            }\n" +
                        "//        }\n");
        stream.println();

        // SET = (zero this row of C) + (PLUS body)
        // After zeroing, MINUS/PLUS/SET all share the same accumulating loops below,
        // varying only by the op token.
        String accOp = (opType == Operation.MINUS) ? "-=" : "+=";
        String alphaPrefix = hasAlpha ? "alpha*" : "";

        stream.print(
                "        final int kEnd4 = widthA & ~3;\n" +
                        "\n" +
                        "        for (int i = 0; i < heightA; i++) {\n" +
                        "            final int aRow = offsetA + i*strideA;\n" +
                        "            final int rowC = offsetC + i*strideC;\n");

        if (opType == Operation.SET) {
            stream.print(
                    "            // SET: zero this row of C so the accumulating body below produces a clean store.\n" +
                            "            for (int j = 0; j < widthC; j++) {\n" +
                            "                dataC[rowC + j] = 0.0;\n" +
                            "            }\n");
        }

        stream.print(
                "            int k = 0;\n" +
                        "            for (; k < kEnd4; k += 4) {\n" +
                        "                double a0 = " + alphaPrefix + "dataA[aRow + k    ];\n" +
                        "                double a1 = " + alphaPrefix + "dataA[aRow + k + 1];\n" +
                        "                double a2 = " + alphaPrefix + "dataA[aRow + k + 2];\n" +
                        "                double a3 = " + alphaPrefix + "dataA[aRow + k + 3];\n" +
                        "                final int b0 = offsetB + (k    )*strideB;\n" +
                        "                final int b1 = offsetB + (k + 1)*strideB;\n" +
                        "                final int b2 = offsetB + (k + 2)*strideB;\n" +
                        "                final int b3 = offsetB + (k + 3)*strideB;\n" +
                        "                for (int j = 0; j < widthC; j++) {\n" +
                        "                    dataC[rowC + j] " + accOp + " a0*dataB[b0 + j]\n" +
                        "                            + a1*dataB[b1 + j]\n" +
                        "                            + a2*dataB[b2 + j]\n" +
                        "                            + a3*dataB[b3 + j];\n" +
                        "                }\n" +
                        "            }\n" +
                        "            // k tail\n" +
                        "            for (; k < widthA; k++) {\n" +
                        "                double valA = " + alphaPrefix + "dataA[aRow + k];\n" +
                        "                final int b = offsetB + k*strideB;\n" +
                        "                for (int j = 0; j < widthC; j++) {\n" +
                        "                    dataC[rowC + j] " + accOp + " valA*dataB[b + j];\n" +
                        "                }\n" +
                        "            }\n" +
                        "        }\n");

        stream.println("    }");
    }

    /// TransA shape: C op A^T * B
    /// Pattern: ijk + JB=4 dot-product. For SET, the dot-product form means accumulators
    /// start at 0 and the single store unconditionally uses `=` -- no "first k" branch needed.
    /// Alpha (when present) pre-multiplies valA in the inner k-loop.
    private void print_multTransA( boolean hasAlpha, Operation opType ) {

        createHeader(hasAlpha, opType, true, false);

        stream.print(
                "//        for( int i = 0; i < widthA; i++ ) {\n" +
                        "//            for( int k = 0; k < heightA; k++ ) {\n" +
                        "//                double valA = " + (hasAlpha ? "alpha*" : "") + "dataA[k*widthA + i + indexA];\n" +
                        "//                for( int j = 0; j < widthC; j++ ) {\n" +
                        "//                    dataC[ i*widthC + j + indexC ] " + opString(opType) + " valA * dataB[k*widthC + j + indexB];\n" +
                        "//                }\n" +
                        "//            }\n" +
                        "//        }\n");
        stream.println();

        String op = opString(opType);
        String alphaPrefix = hasAlpha ? "alpha*" : "";

        stream.print(
                "        final int jEnd4 = widthC & ~3;\n" +
                        "\n" +
                        "        for (int i = 0; i < widthA; i++) {\n" +
                        "            int j = 0;\n" +
                        "            for (; j < jEnd4; j += 4) {\n" +
                        "                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;\n" +
                        "                int aIdx = offsetA + i;\n" +
                        "                int bIdx = offsetB + j;\n" +
                        "                final int aEnd = aIdx + heightA*strideA;\n" +
                        "                while (aIdx != aEnd) {\n" +
                        "                    double valA = " + alphaPrefix + "dataA[aIdx];\n" +
                        "                    s0 += valA*dataB[bIdx];\n" +
                        "                    s1 += valA*dataB[bIdx + 1];\n" +
                        "                    s2 += valA*dataB[bIdx + 2];\n" +
                        "                    s3 += valA*dataB[bIdx + 3];\n" +
                        "                    aIdx += strideA;\n" +
                        "                    bIdx += strideB;\n" +
                        "                }\n" +
                        "                int cIdx = offsetC + i*strideC + j;\n" +
                        "                dataC[cIdx    ] " + op + " s0;\n" +
                        "                dataC[cIdx + 1] " + op + " s1;\n" +
                        "                dataC[cIdx + 2] " + op + " s2;\n" +
                        "                dataC[cIdx + 3] " + op + " s3;\n" +
                        "            }\n" +
                        "            for (; j < widthC; j++) {\n" +
                        "                double s = 0.0;\n" +
                        "                int aIdx = offsetA + i;\n" +
                        "                int bIdx = offsetB + j;\n" +
                        "                final int aEnd = aIdx + heightA*strideA;\n" +
                        "                while (aIdx != aEnd) {\n" +
                        "                    s += " + alphaPrefix + "dataA[aIdx]*dataB[bIdx];\n" +
                        "                    aIdx += strideA;\n" +
                        "                    bIdx += strideB;\n" +
                        "                }\n" +
                        "                dataC[offsetC + i*strideC + j] " + op + " s;\n" +
                        "            }\n" +
                        "        }\n");

        stream.println("    }");
    }

    /// TransB shape: C op A * B^T
    /// Pattern: JB=4 row-blocking on j. Both panels read contiguously in k.
    /// Alpha (when present) post-multiplies the accumulators at store time so the
    /// inner FMA chain stays clean.
    private void print_multTransB( boolean hasAlpha, Operation opType ) {

        createHeader(hasAlpha, opType, false, true);

        stream.print(
                "//        for (int i = 0; i < heightA; i++) {\n" +
                        "//            for (int j = 0; j < widthC; j++) {\n" +
                        "//                double val = 0;\n" +
                        "//                for (int k = 0; k < widthA; k++) {\n" +
                        "//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];\n" +
                        "//                }\n" +
                        "//                dataC[i*widthC + j + indexC] " + opString(opType) + " " + (hasAlpha ? "alpha*" : "") + "val;\n" +
                        "//            }\n" +
                        "//        }\n");
        stream.println();

        String op = opString(opType);
        // For TransB, alpha goes at the store site (post-multiply on the accumulator).
        String alphaStore = hasAlpha ? "alpha*" : "";

        stream.print(
                "        final int jEnd4 = widthC & ~3;\n" +
                        "\n" +
                        "        for (int i = 0; i < heightA; i++) {\n" +
                        "            final int aRow = offsetA + i*strideA;\n" +
                        "            final int aEnd = aRow + widthA;\n" +
                        "            int j = 0;\n" +
                        "            for (; j < jEnd4; j += 4) {\n" +
                        "                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;\n" +
                        "                int a = aRow;\n" +
                        "                int b0 = offsetB + (j    )*strideB;\n" +
                        "                int b1 = offsetB + (j + 1)*strideB;\n" +
                        "                int b2 = offsetB + (j + 2)*strideB;\n" +
                        "                int b3 = offsetB + (j + 3)*strideB;\n" +
                        "                while (a != aEnd) {\n" +
                        "                    double valA = dataA[a++];\n" +
                        "                    s0 += valA*dataB[b0++];\n" +
                        "                    s1 += valA*dataB[b1++];\n" +
                        "                    s2 += valA*dataB[b2++];\n" +
                        "                    s3 += valA*dataB[b3++];\n" +
                        "                }\n" +
                        "                int cIdx = offsetC + i*strideC + j;\n" +
                        "                dataC[cIdx    ] " + op + " " + alphaStore + "s0;\n" +
                        "                dataC[cIdx + 1] " + op + " " + alphaStore + "s1;\n" +
                        "                dataC[cIdx + 2] " + op + " " + alphaStore + "s2;\n" +
                        "                dataC[cIdx + 3] " + op + " " + alphaStore + "s3;\n" +
                        "            }\n" +
                        "            for (; j < widthC; j++) {\n" +
                        "                double s = 0.0;\n" +
                        "                int a = aRow;\n" +
                        "                int b = offsetB + j*strideB;\n" +
                        "                while (a != aEnd) {\n" +
                        "                    s += dataA[a++]*dataB[b++];\n" +
                        "                }\n" +
                        "                dataC[offsetC + i*strideC + j] " + op + " " + alphaStore + "s;\n" +
                        "            }\n" +
                        "        }\n");

        stream.println("    }");
    }

    private void printDoc( boolean hasAlpha, Operation opType, boolean transA, boolean transB ) {
        String alphaString = hasAlpha ? " &alpha; " : "";
        String transAString = transA ? "<sup>T</sup>" : "";
        String transBString = transB ? "<sup>T</sup>" : "";

        String opTypeString = switch (opType) {
            case MINUS -> "C - ";
            case PLUS -> "C + ";
            case SET -> "";
            default -> throw new RuntimeException("Unknown optype");
        };

        stream.println();
        stream.print(
                        "    /// C = " + opTypeString + alphaString + "A" + transAString + " \\* B" + transBString + "\n");
    }

    private String funcName( Operation opType, boolean transA, boolean transB ) {
        String name = "tileMult" + opName(opType);
        if (transA && transB) name += "TransAB";
        else if (transA) name += "TransA";
        else if (transB) name += "TransB";
        return name;
    }

    private void createHeader( boolean hasAlpha, Operation opType, boolean transA, boolean transB ) {
        printDoc(hasAlpha, opType, transA, transB);
        String alphaParam = hasAlpha ? " double alpha," : "";
        stream.print(
                "    public static void " + funcName(opType, transA, transB) + "(" + alphaParam + " final double[] dataA, final double[] dataB, final double[] dataC,\n" +
                        "                                     final int heightA, final int widthA, final int widthC,\n" +
                        "                                     int strideA, int strideB, int strideC,\n" +
                        "                                     int offsetA, int offsetB, int offsetC) {\n");
    }

    private void printDelegate( boolean hasAlpha, Operation opType, boolean transA, boolean transB ) {
        printDoc(hasAlpha, opType, transA, transB);
        String name = funcName(opType, transA, transB);
        String alphaParam = hasAlpha ? " double alpha," : "";
        String alphaArg = hasAlpha ? "alpha, " : "";
        String strideB = transB ? "widthA" : "widthC";
        stream.print(
                "    public static void " + name + "(" + alphaParam + " final double[] dataA, final double[] dataB, final double[] dataC,\n" +
                        "                                     final int heightA, final int widthA, final int widthC,\n" +
                        "                                     int offsetA, int offsetB, int offsetC) {\n" +
                        "        " + name + "(" + alphaArg + "dataA, dataB, dataC, heightA, widthA, widthC, widthA, " + strideB + ", widthC, offsetA, offsetB, offsetC);\n" +
                        "    }\n");
    }

    private String opString( Operation opType ) {
        return switch (opType) {
            case MINUS -> "-=";
            case PLUS -> "+=";
            case SET -> "=";
            default -> throw new RuntimeException("Unknown opType " + opType);
        };
    }

    private String opName( Operation opType ) {
        return switch (opType) {
            case MINUS -> "Minus";
            case PLUS -> "Plus";
            case SET -> "Set";
            default -> throw new RuntimeException("Unknown opType " + opType);
        };
    }

    private enum Operation {
        /** Add results to output matrix */
        PLUS,
        /** Subtract results from output matrix */
        MINUS,
        /** set output matrix to results */
        SET
    }

    public static void main( String[] args ) throws FileNotFoundException {
        var app = new GeneratorTileMultiplication("InnerMultiplication_DDRB");
        app.createClass();
        System.out.println("Done generating class");
    }
}
