/*
 * Copyright (c) 2026, Peter Abeles. All Rights Reserved.
 *
 * This file is part of Efficient Java Matrix Library (EJML).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ejml.dense.block;

import javax.annotation.Generated;

/// Matrix multiplication for the inner row major blocks, typically inside [DMatrixRBlock].
///
/// Generated by GeneratorTileMultiplication. Do not modify directly.
@Generated("org.ejml.dense.block.GeneratorTileMultiplication")
public class TileMultiplication_F64 {

    /// C = C + A \* B
    public static void tileMultPlus( final double[] dataA, final double[] dataB, final double[] dataC,
                                     final int heightA, final int widthA, final int widthC,
                                     int strideA, int strideB, int strideC,
                                     int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < heightA; i++ ) {
//            for( int k = 0; k < widthA; k++ ) {
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] += dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int kEnd4 = widthA & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int rowC = offsetC + i*strideC;
            int k = 0;
            for (; k < kEnd4; k += 4) {
                double a0 = dataA[aRow + k];
                double a1 = dataA[aRow + k + 1];
                double a2 = dataA[aRow + k + 2];
                double a3 = dataA[aRow + k + 3];
                final int b0 = offsetB + (k)*strideB;
                final int b1 = offsetB + (k + 1)*strideB;
                final int b2 = offsetB + (k + 2)*strideB;
                final int b3 = offsetB + (k + 3)*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += a0*dataB[b0 + j]
                            + a1*dataB[b1 + j]
                            + a2*dataB[b2 + j]
                            + a3*dataB[b3 + j];
                }
            }
            // k tail
            for (; k < widthA; k++) {
                double valA = dataA[aRow + k];
                final int b = offsetB + k*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += valA*dataB[b + j];
                }
            }
        }
    }

    /// C = C + A \* B
    public static void tileMultPlus( final double[] dataA, final double[] dataB, final double[] dataC,
                                     final int heightA, final int widthA, final int widthC,
                                     int offsetA, int offsetB, int offsetC ) {
        tileMultPlus(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C + A<sup>T</sup> \* B
    public static void tileMultPlusTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int strideA, int strideB, int strideC,
                                           int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < widthA; i++ ) {
//            for( int k = 0; k < heightA; k++ ) {
//                double valA = dataA[k*widthA + i + indexA];
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] += valA * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < widthA; i++) {
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    double valA = dataA[aIdx];
                    s0 += valA*dataB[bIdx];
                    s1 += valA*dataB[bIdx + 1];
                    s2 += valA*dataB[bIdx + 2];
                    s3 += valA*dataB[bIdx + 3];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] += s0;
                dataC[cIdx + 1] += s1;
                dataC[cIdx + 2] += s2;
                dataC[cIdx + 3] += s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    s += dataA[aIdx]*dataB[bIdx];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                dataC[offsetC + i*strideC + j] += s;
            }
        }
    }

    /// C = C + A<sup>T</sup> \* B
    public static void tileMultPlusTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int offsetA, int offsetB, int offsetC ) {
        tileMultPlusTransA(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C + A \* B<sup>T</sup>
    public static void tileMultPlusTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int strideA, int strideB, int strideC,
                                           int offsetA, int offsetB, int offsetC ) {
//        for (int i = 0; i < heightA; i++) {
//            for (int j = 0; j < widthC; j++) {
//                double val = 0;
//                for (int k = 0; k < widthA; k++) {
//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];
//                }
//                dataC[i*widthC + j + indexC] += val;
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int aEnd = aRow + widthA;
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int a = aRow;
                int b0 = offsetB + (j)*strideB;
                int b1 = offsetB + (j + 1)*strideB;
                int b2 = offsetB + (j + 2)*strideB;
                int b3 = offsetB + (j + 3)*strideB;
                while (a != aEnd) {
                    double valA = dataA[a++];
                    s0 += valA*dataB[b0++];
                    s1 += valA*dataB[b1++];
                    s2 += valA*dataB[b2++];
                    s3 += valA*dataB[b3++];
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] += s0;
                dataC[cIdx + 1] += s1;
                dataC[cIdx + 2] += s2;
                dataC[cIdx + 3] += s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int a = aRow;
                int b = offsetB + j*strideB;
                while (a != aEnd) {
                    s += dataA[a++]*dataB[b++];
                }
                dataC[offsetC + i*strideC + j] += s;
            }
        }
    }

    /// C = C + A \* B<sup>T</sup>
    public static void tileMultPlusTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int offsetA, int offsetB, int offsetC ) {
        tileMultPlusTransB(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthA, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C - A \* B
    public static void tileMultMinus( final double[] dataA, final double[] dataB, final double[] dataC,
                                      final int heightA, final int widthA, final int widthC,
                                      int strideA, int strideB, int strideC,
                                      int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < heightA; i++ ) {
//            for( int k = 0; k < widthA; k++ ) {
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] -= dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int kEnd4 = widthA & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int rowC = offsetC + i*strideC;
            int k = 0;
            for (; k < kEnd4; k += 4) {
                double a0 = dataA[aRow + k];
                double a1 = dataA[aRow + k + 1];
                double a2 = dataA[aRow + k + 2];
                double a3 = dataA[aRow + k + 3];
                final int b0 = offsetB + (k)*strideB;
                final int b1 = offsetB + (k + 1)*strideB;
                final int b2 = offsetB + (k + 2)*strideB;
                final int b3 = offsetB + (k + 3)*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] -= a0*dataB[b0 + j]
                            + a1*dataB[b1 + j]
                            + a2*dataB[b2 + j]
                            + a3*dataB[b3 + j];
                }
            }
            // k tail
            for (; k < widthA; k++) {
                double valA = dataA[aRow + k];
                final int b = offsetB + k*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] -= valA*dataB[b + j];
                }
            }
        }
    }

    /// C = C - A \* B
    public static void tileMultMinus( final double[] dataA, final double[] dataB, final double[] dataC,
                                      final int heightA, final int widthA, final int widthC,
                                      int offsetA, int offsetB, int offsetC ) {
        tileMultMinus(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C - A<sup>T</sup> \* B
    public static void tileMultMinusTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                            final int heightA, final int widthA, final int widthC,
                                            int strideA, int strideB, int strideC,
                                            int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < widthA; i++ ) {
//            for( int k = 0; k < heightA; k++ ) {
//                double valA = dataA[k*widthA + i + indexA];
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] -= valA * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < widthA; i++) {
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    double valA = dataA[aIdx];
                    s0 += valA*dataB[bIdx];
                    s1 += valA*dataB[bIdx + 1];
                    s2 += valA*dataB[bIdx + 2];
                    s3 += valA*dataB[bIdx + 3];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] -= s0;
                dataC[cIdx + 1] -= s1;
                dataC[cIdx + 2] -= s2;
                dataC[cIdx + 3] -= s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    s += dataA[aIdx]*dataB[bIdx];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                dataC[offsetC + i*strideC + j] -= s;
            }
        }
    }

    /// C = C - A<sup>T</sup> \* B
    public static void tileMultMinusTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                            final int heightA, final int widthA, final int widthC,
                                            int offsetA, int offsetB, int offsetC ) {
        tileMultMinusTransA(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C - A \* B<sup>T</sup>
    public static void tileMultMinusTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                            final int heightA, final int widthA, final int widthC,
                                            int strideA, int strideB, int strideC,
                                            int offsetA, int offsetB, int offsetC ) {
//        for (int i = 0; i < heightA; i++) {
//            for (int j = 0; j < widthC; j++) {
//                double val = 0;
//                for (int k = 0; k < widthA; k++) {
//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];
//                }
//                dataC[i*widthC + j + indexC] -= val;
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int aEnd = aRow + widthA;
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int a = aRow;
                int b0 = offsetB + (j)*strideB;
                int b1 = offsetB + (j + 1)*strideB;
                int b2 = offsetB + (j + 2)*strideB;
                int b3 = offsetB + (j + 3)*strideB;
                while (a != aEnd) {
                    double valA = dataA[a++];
                    s0 += valA*dataB[b0++];
                    s1 += valA*dataB[b1++];
                    s2 += valA*dataB[b2++];
                    s3 += valA*dataB[b3++];
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] -= s0;
                dataC[cIdx + 1] -= s1;
                dataC[cIdx + 2] -= s2;
                dataC[cIdx + 3] -= s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int a = aRow;
                int b = offsetB + j*strideB;
                while (a != aEnd) {
                    s += dataA[a++]*dataB[b++];
                }
                dataC[offsetC + i*strideC + j] -= s;
            }
        }
    }

    /// C = C - A \* B<sup>T</sup>
    public static void tileMultMinusTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                            final int heightA, final int widthA, final int widthC,
                                            int offsetA, int offsetB, int offsetC ) {
        tileMultMinusTransB(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthA, widthC, offsetA, offsetB, offsetC);
    }

    /// C = A \* B
    public static void tileMultSet( final double[] dataA, final double[] dataB, final double[] dataC,
                                    final int heightA, final int widthA, final int widthC,
                                    int strideA, int strideB, int strideC,
                                    int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < heightA; i++ ) {
//            for( int k = 0; k < widthA; k++ ) {
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] = dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int kEnd4 = widthA & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int rowC = offsetC + i*strideC;
            // SET: zero this row of C so the accumulating body below produces a clean store.
            for (int j = 0; j < widthC; j++) {
                dataC[rowC + j] = 0.0;
            }
            int k = 0;
            for (; k < kEnd4; k += 4) {
                double a0 = dataA[aRow + k];
                double a1 = dataA[aRow + k + 1];
                double a2 = dataA[aRow + k + 2];
                double a3 = dataA[aRow + k + 3];
                final int b0 = offsetB + (k)*strideB;
                final int b1 = offsetB + (k + 1)*strideB;
                final int b2 = offsetB + (k + 2)*strideB;
                final int b3 = offsetB + (k + 3)*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += a0*dataB[b0 + j]
                            + a1*dataB[b1 + j]
                            + a2*dataB[b2 + j]
                            + a3*dataB[b3 + j];
                }
            }
            // k tail
            for (; k < widthA; k++) {
                double valA = dataA[aRow + k];
                final int b = offsetB + k*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += valA*dataB[b + j];
                }
            }
        }
    }

    /// C = A \* B
    public static void tileMultSet( final double[] dataA, final double[] dataB, final double[] dataC,
                                    final int heightA, final int widthA, final int widthC,
                                    int offsetA, int offsetB, int offsetC ) {
        tileMultSet(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = A<sup>T</sup> \* B
    public static void tileMultSetTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int strideA, int strideB, int strideC,
                                          int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < widthA; i++ ) {
//            for( int k = 0; k < heightA; k++ ) {
//                double valA = dataA[k*widthA + i + indexA];
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] = valA * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < widthA; i++) {
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    double valA = dataA[aIdx];
                    s0 += valA*dataB[bIdx];
                    s1 += valA*dataB[bIdx + 1];
                    s2 += valA*dataB[bIdx + 2];
                    s3 += valA*dataB[bIdx + 3];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] = s0;
                dataC[cIdx + 1] = s1;
                dataC[cIdx + 2] = s2;
                dataC[cIdx + 3] = s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    s += dataA[aIdx]*dataB[bIdx];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                dataC[offsetC + i*strideC + j] = s;
            }
        }
    }

    /// C = A<sup>T</sup> \* B
    public static void tileMultSetTransA( final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int offsetA, int offsetB, int offsetC ) {
        tileMultSetTransA(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = A \* B<sup>T</sup>
    public static void tileMultSetTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int strideA, int strideB, int strideC,
                                          int offsetA, int offsetB, int offsetC ) {
//        for (int i = 0; i < heightA; i++) {
//            for (int j = 0; j < widthC; j++) {
//                double val = 0;
//                for (int k = 0; k < widthA; k++) {
//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];
//                }
//                dataC[i*widthC + j + indexC] = val;
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int aEnd = aRow + widthA;
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int a = aRow;
                int b0 = offsetB + (j)*strideB;
                int b1 = offsetB + (j + 1)*strideB;
                int b2 = offsetB + (j + 2)*strideB;
                int b3 = offsetB + (j + 3)*strideB;
                while (a != aEnd) {
                    double valA = dataA[a++];
                    s0 += valA*dataB[b0++];
                    s1 += valA*dataB[b1++];
                    s2 += valA*dataB[b2++];
                    s3 += valA*dataB[b3++];
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] = s0;
                dataC[cIdx + 1] = s1;
                dataC[cIdx + 2] = s2;
                dataC[cIdx + 3] = s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int a = aRow;
                int b = offsetB + j*strideB;
                while (a != aEnd) {
                    s += dataA[a++]*dataB[b++];
                }
                dataC[offsetC + i*strideC + j] = s;
            }
        }
    }

    /// C = A \* B<sup>T</sup>
    public static void tileMultSetTransB( final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int offsetA, int offsetB, int offsetC ) {
        tileMultSetTransB(dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthA, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C +  &alpha; A \* B
    public static void tileMultPlus( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                     final int heightA, final int widthA, final int widthC,
                                     int strideA, int strideB, int strideC,
                                     int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < heightA; i++ ) {
//            for( int k = 0; k < widthA; k++ ) {
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] += alpha * dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int kEnd4 = widthA & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int rowC = offsetC + i*strideC;
            int k = 0;
            for (; k < kEnd4; k += 4) {
                double a0 = alpha*dataA[aRow + k];
                double a1 = alpha*dataA[aRow + k + 1];
                double a2 = alpha*dataA[aRow + k + 2];
                double a3 = alpha*dataA[aRow + k + 3];
                final int b0 = offsetB + (k)*strideB;
                final int b1 = offsetB + (k + 1)*strideB;
                final int b2 = offsetB + (k + 2)*strideB;
                final int b3 = offsetB + (k + 3)*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += a0*dataB[b0 + j]
                            + a1*dataB[b1 + j]
                            + a2*dataB[b2 + j]
                            + a3*dataB[b3 + j];
                }
            }
            // k tail
            for (; k < widthA; k++) {
                double valA = alpha*dataA[aRow + k];
                final int b = offsetB + k*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += valA*dataB[b + j];
                }
            }
        }
    }

    /// C = C +  &alpha; A \* B
    public static void tileMultPlus( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                     final int heightA, final int widthA, final int widthC,
                                     int offsetA, int offsetB, int offsetC ) {
        tileMultPlus(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C +  &alpha; A<sup>T</sup> \* B
    public static void tileMultPlusTransA( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int strideA, int strideB, int strideC,
                                           int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < widthA; i++ ) {
//            for( int k = 0; k < heightA; k++ ) {
//                double valA = alpha*dataA[k*widthA + i + indexA];
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] += valA * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < widthA; i++) {
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    double valA = alpha*dataA[aIdx];
                    s0 += valA*dataB[bIdx];
                    s1 += valA*dataB[bIdx + 1];
                    s2 += valA*dataB[bIdx + 2];
                    s3 += valA*dataB[bIdx + 3];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] += s0;
                dataC[cIdx + 1] += s1;
                dataC[cIdx + 2] += s2;
                dataC[cIdx + 3] += s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    s += alpha*dataA[aIdx]*dataB[bIdx];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                dataC[offsetC + i*strideC + j] += s;
            }
        }
    }

    /// C = C +  &alpha; A<sup>T</sup> \* B
    public static void tileMultPlusTransA( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int offsetA, int offsetB, int offsetC ) {
        tileMultPlusTransA(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C = C +  &alpha; A \* B<sup>T</sup>
    public static void tileMultPlusTransB( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int strideA, int strideB, int strideC,
                                           int offsetA, int offsetB, int offsetC ) {
//        for (int i = 0; i < heightA; i++) {
//            for (int j = 0; j < widthC; j++) {
//                double val = 0;
//                for (int k = 0; k < widthA; k++) {
//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];
//                }
//                dataC[i*widthC + j + indexC] += alpha*val;
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int aEnd = aRow + widthA;
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int a = aRow;
                int b0 = offsetB + (j)*strideB;
                int b1 = offsetB + (j + 1)*strideB;
                int b2 = offsetB + (j + 2)*strideB;
                int b3 = offsetB + (j + 3)*strideB;
                while (a != aEnd) {
                    double valA = dataA[a++];
                    s0 += valA*dataB[b0++];
                    s1 += valA*dataB[b1++];
                    s2 += valA*dataB[b2++];
                    s3 += valA*dataB[b3++];
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] += alpha*s0;
                dataC[cIdx + 1] += alpha*s1;
                dataC[cIdx + 2] += alpha*s2;
                dataC[cIdx + 3] += alpha*s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int a = aRow;
                int b = offsetB + j*strideB;
                while (a != aEnd) {
                    s += dataA[a++]*dataB[b++];
                }
                dataC[offsetC + i*strideC + j] += alpha*s;
            }
        }
    }

    /// C = C +  &alpha; A \* B<sup>T</sup>
    public static void tileMultPlusTransB( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                           final int heightA, final int widthA, final int widthC,
                                           int offsetA, int offsetB, int offsetC ) {
        tileMultPlusTransB(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthA, widthC, offsetA, offsetB, offsetC);
    }

    /// C =  &alpha; A \* B
    public static void tileMultSet( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                    final int heightA, final int widthA, final int widthC,
                                    int strideA, int strideB, int strideC,
                                    int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < heightA; i++ ) {
//            for( int k = 0; k < widthA; k++ ) {
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] = alpha * dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int kEnd4 = widthA & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int rowC = offsetC + i*strideC;
            // SET: zero this row of C so the accumulating body below produces a clean store.
            for (int j = 0; j < widthC; j++) {
                dataC[rowC + j] = 0.0;
            }
            int k = 0;
            for (; k < kEnd4; k += 4) {
                double a0 = alpha*dataA[aRow + k];
                double a1 = alpha*dataA[aRow + k + 1];
                double a2 = alpha*dataA[aRow + k + 2];
                double a3 = alpha*dataA[aRow + k + 3];
                final int b0 = offsetB + (k)*strideB;
                final int b1 = offsetB + (k + 1)*strideB;
                final int b2 = offsetB + (k + 2)*strideB;
                final int b3 = offsetB + (k + 3)*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += a0*dataB[b0 + j]
                            + a1*dataB[b1 + j]
                            + a2*dataB[b2 + j]
                            + a3*dataB[b3 + j];
                }
            }
            // k tail
            for (; k < widthA; k++) {
                double valA = alpha*dataA[aRow + k];
                final int b = offsetB + k*strideB;
                for (int j = 0; j < widthC; j++) {
                    dataC[rowC + j] += valA*dataB[b + j];
                }
            }
        }
    }

    /// C =  &alpha; A \* B
    public static void tileMultSet( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                    final int heightA, final int widthA, final int widthC,
                                    int offsetA, int offsetB, int offsetC ) {
        tileMultSet(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C =  &alpha; A<sup>T</sup> \* B
    public static void tileMultSetTransA( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int strideA, int strideB, int strideC,
                                          int offsetA, int offsetB, int offsetC ) {
//        for( int i = 0; i < widthA; i++ ) {
//            for( int k = 0; k < heightA; k++ ) {
//                double valA = alpha*dataA[k*widthA + i + indexA];
//                for( int j = 0; j < widthC; j++ ) {
//                    dataC[ i*widthC + j + indexC ] = valA * dataB[k*widthC + j + indexB];
//                }
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < widthA; i++) {
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    double valA = alpha*dataA[aIdx];
                    s0 += valA*dataB[bIdx];
                    s1 += valA*dataB[bIdx + 1];
                    s2 += valA*dataB[bIdx + 2];
                    s3 += valA*dataB[bIdx + 3];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] = s0;
                dataC[cIdx + 1] = s1;
                dataC[cIdx + 2] = s2;
                dataC[cIdx + 3] = s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int aIdx = offsetA + i;
                int bIdx = offsetB + j;
                final int aEnd = aIdx + heightA*strideA;
                while (aIdx != aEnd) {
                    s += alpha*dataA[aIdx]*dataB[bIdx];
                    aIdx += strideA;
                    bIdx += strideB;
                }
                dataC[offsetC + i*strideC + j] = s;
            }
        }
    }

    /// C =  &alpha; A<sup>T</sup> \* B
    public static void tileMultSetTransA( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int offsetA, int offsetB, int offsetC ) {
        tileMultSetTransA(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthC, widthC, offsetA, offsetB, offsetC);
    }

    /// C =  &alpha; A \* B<sup>T</sup>
    public static void tileMultSetTransB( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int strideA, int strideB, int strideC,
                                          int offsetA, int offsetB, int offsetC ) {
//        for (int i = 0; i < heightA; i++) {
//            for (int j = 0; j < widthC; j++) {
//                double val = 0;
//                for (int k = 0; k < widthA; k++) {
//                    val += dataA[i*widthA + k + indexA]*dataB[j*widthA + k + indexB];
//                }
//                dataC[i*widthC + j + indexC] = alpha*val;
//            }
//        }

        final int jEnd4 = widthC & ~3;

        for (int i = 0; i < heightA; i++) {
            final int aRow = offsetA + i*strideA;
            final int aEnd = aRow + widthA;
            int j = 0;
            for (; j < jEnd4; j += 4) {
                double s0 = 0.0, s1 = 0.0, s2 = 0.0, s3 = 0.0;
                int a = aRow;
                int b0 = offsetB + (j)*strideB;
                int b1 = offsetB + (j + 1)*strideB;
                int b2 = offsetB + (j + 2)*strideB;
                int b3 = offsetB + (j + 3)*strideB;
                while (a != aEnd) {
                    double valA = dataA[a++];
                    s0 += valA*dataB[b0++];
                    s1 += valA*dataB[b1++];
                    s2 += valA*dataB[b2++];
                    s3 += valA*dataB[b3++];
                }
                int cIdx = offsetC + i*strideC + j;
                dataC[cIdx] = alpha*s0;
                dataC[cIdx + 1] = alpha*s1;
                dataC[cIdx + 2] = alpha*s2;
                dataC[cIdx + 3] = alpha*s3;
            }
            for (; j < widthC; j++) {
                double s = 0.0;
                int a = aRow;
                int b = offsetB + j*strideB;
                while (a != aEnd) {
                    s += dataA[a++]*dataB[b++];
                }
                dataC[offsetC + i*strideC + j] = alpha*s;
            }
        }
    }

    /// C =  &alpha; A \* B<sup>T</sup>
    public static void tileMultSetTransB( double alpha, final double[] dataA, final double[] dataB, final double[] dataC,
                                          final int heightA, final int widthA, final int widthC,
                                          int offsetA, int offsetB, int offsetC ) {
        tileMultSetTransB(alpha, dataA, dataB, dataC, heightA, widthA, widthC, widthA, widthA, widthC, offsetA, offsetB, offsetC);
    }
}
