# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ SNAPSHOT ]
  pull_request:
    branches: [ SNAPSHOT ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Spotless Check
      run: ./gradlew spotlessJavaCheck
    - name: Auto Generate Code
      run: ./gradlew autogenerate
    - name: Gradle Assemble
      run: ./gradlew assemble
    - name: Unit Tests
      run: ./gradlew test
